blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ Questions & Discussions
    url: https://github.com/x-cmd/x-cmd/discussions/new
    about: Use GitHub discussions for message-board style questions and discussions.

  - name: ğŸŸ¢ Join in WeChat (å¾®ä¿¡ç¾¤)
    url: https://x-cmd.com/start/community
    about: Ask questions and discuss with X-CMD team member and other X-CMD users in real time.

  - name: ğŸ‘¾ Join in Discord
    url: https://discord.gg/FXZCP5S74a
    about: Ask questions and discuss with X-CMD team member and other X-CMD users in real time.
  
  - name: âœˆï¸ Join in Telegram
    url: https://t.me/x_cmd
    about: Ask questions and discuss with X-CMD team member and other X-CMD users in real time.
